### ISSUE TITLE
🚀 Roadmap of PaddleYOLO 🚀

### ISSUE THREAD

**Issue by nemonameless** [PaddlePaddle/PaddleYOLO#44]
## Roadmap of PaddleYOLO

This issue is used to collect user's functional requirements and show the future development plan.

Welcome to provide functional requirements and any suggestions through the message, thank you.

此issue用于收集广大用户的功能需求，以及展示之后的研发计划。

欢迎通过留言提供您的功能需求和任何建议，谢谢。

### Roadmap

  - [x] `VOC` dataset Model Zoo and Tutorial
  - [x] Speed up YOLOv5/YOLOv7 training
  - [ ] support DAMO-YOLO

### Collected features

  - [ ] -

**Comment by clintonfang** [comment]
大概什么时候能支持Yolov8或者Yolov5这种Anchor Free的模型训练？

**Comment by nemonameless** [comment]
> 大概什么时候能支持Yolov8或者Yolov5这种Anchor Free的模型训练？

https://github.com/PaddlePaddle/PaddleYOLO/issues/103

谢谢关注。由于工作安排问题，我们是将YOLOv8的训练实现放到了 https://github.com/PaddlePaddle/Paddle/issues/51281#detection 里，具体比赛可看[PaddlePaddle Hackathon 飞桨黑客马拉松第四期](https://aistudio.baidu.com/aistudio/competition/detail/776/0/introduction)。我们也会及时评估选手的进度，必要时辅助选手或自行实现，由于比赛原因预计4月底才可以公布实现。

就当前性能来看，PPYOLOE+ 模型只训80epoch的情况下还是可以略胜YOLOv8的500epoch，你可以训更多epoch试试。

此外PPYOLOE+的小目标、旋转框、密集检测、半监督检测、检测蒸馏、tiny版本、obj365预训练、transformer等超大型backbone、各种人车工业垂类应用都很齐全，欢迎使用。
https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/ppyoloe
https://github.com/PaddlePaddle/PaddleDetection/releases/tag/v2.6.0

以及最新的 RT-DETR，https://github.com/PaddlePaddle/PaddleDetection/issues/8114
https://mp.weixin.qq.com/s/psZm6-ZtbW5p5yZFpOA0Og 有公众号也发布了可以参考下。

**Comment by WilliamQf-AI** [comment]
扫描文档图片边框检测功能

**Comment by nemonameless** [comment]
> 扫描文档图片边框检测功能

有类似yolo有这个功能的吗？可以推荐下链接。另外这个是不是属于OCR的内容？可以问 https://github.com/PaddlePaddle/PaddleOCR/issues

**Comment by huilin66** [comment]
会支持yolor吗

**Comment by nemonameless** [comment]
> 会支持yolor吗

您好，这个模型太久远，暂无计划支持。可考虑使用PPYOLOE+和RT-DETR
